ALTER TABLE contas ADD COLUMN IF NOT EXISTS recorrente     BOOLEAN DEFAULT FALSE;
ALTER TABLE contas ADD COLUMN IF NOT EXISTS conta_pai_id  INTEGER REFERENCES contas(id) ON DELETE CASCADE;
ALTER TABLE contas ADD COLUMN IF NOT EXISTS cartao_vinculado VARCHAR(100);
