ALTER TABLE contas ADD COLUMN IF NOT EXISTS forma_pagamento VARCHAR(30);
ALTER TABLE contas ADD COLUMN IF NOT EXISTS num_parcelas INT;
ALTER TABLE contas ADD COLUMN IF NOT EXISTS tipo_pagamento VARCHAR(20);
