CREATE TABLE IF NOT EXISTS cartoes (
  id SERIAL PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  conta_pagamento VARCHAR(150),
  cor VARCHAR(7) DEFAULT '#6366f1',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE gastos ADD COLUMN IF NOT EXISTS cartao_id INTEGER REFERENCES cartoes(id) ON DELETE SET NULL;
