services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: samuell_financas
      POSTGRES_USER: samuel
      POSTGRES_PASSWORD: financas123
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
